spring:
  application.name: notes_api
  datasource:
    url: jdbc:postgresql://localhost:5432/notes_dev
    username: postgres
    password: dperezba
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
server:
  servlet:
    context-path: /api/v1
